# Exercise 03: Matrix Operations
# Cluster 2 - Linear Algebra + NumPy
# Core concepts: Transpose, Dot Product, Matrix Rank

In [22]:
import numpy as np

# Create a simple matrix — 3 applicants, 3 attributes
applicants = np.array([
    [5, 85, 90],
    [3, 92, 75],
    [7, 78, 88]
])

print("Original matrix (applicants × attributes):")
print(applicants)
print(f"Shape: {applicants.shape}")

Original matrix (applicants × attributes):
[[ 5 85 90]
 [ 3 92 75]
 [ 7 78 88]]
Shape: (3, 3)


In [12]:
B=np.array([
    [2,10],
    [7,19],
    [7,9],
    [5,32],
    [9,14]
])
print("Original shape:", B.shape)
print("Transposed shape:", B.T.shape)
print("\nTranspose:\n", B.T)

Original shape: (5, 2)
Transposed shape: (2, 5)

Transpose:
 [[ 2  7  7  5  9]
 [10 19  9 32 14]]


In [14]:
# Two candidate feature vectors
alice = np.array([5, 82, 7, 1])
bob   = np.array([3, 91, 8, 0])

# Dot product — three ways
print(np.dot(alice, bob))
print(alice @ bob)
print(sum(alice * bob))

# Now with weights that sum to 1.0
weights = np.array([0.1, 0.4, 0.4, 0.1])
print("\nAlice score:", alice @ weights)
print("Bob score:  ", bob @ weights)
print("Weights sum:", weights.sum())

7533
7533
7533

Alice score: 36.2
Bob score:   39.9
Weights sum: 1.0


In [16]:
# Feature matrix: 4 candidates × 4 features
X = np.array([
    [5, 82, 7, 1],
    [3, 91, 8, 0],
    [7, 78, 6, 1],
    [4, 85, 9, 0]
])

# Fair weights (sum to 1.0)
w_fair = np.array([0.2, 0.35, 0.35, 0.1])

# Biased weights (referral weighted 3x more)
w_biased = np.array([0.1, 0.3, 0.3, 0.3])

# Scores for all candidates
scores_fair   = X @ w_fair
scores_biased = X @ w_biased

print("Fair scores:  ", scores_fair)
print("Biased scores:", scores_biased)
print("\nRanking (fair):  ", np.argsort(-scores_fair))
print("Ranking (biased):", np.argsort(-scores_biased))

# Who has referral? Candidates 0 and 2
print("\nCandidates with referral:", np.where(X[:, 3] == 1)[0])

Fair scores:   [32.25 35.25 30.9  33.7 ]
Biased scores: [27.5 30.  26.2 28.6]

Ranking (fair):   [1 3 0 2]
Ranking (biased): [1 3 0 2]

Candidates with referral: [0 2]


When biased weights prioritize referral at 0.3 instead of 0.1, candidates with referrals (0 and 2) see their overall scores drop from 32.25/30.9 to 27.5/26.2, while candidates without referrals drop less, creating a system that paradoxically penalizes the very people the bias was supposed to favour. Under the EU AI Act High-Risk classification, this is a governance failure because even though final rankings don't change, the system encodes an unjustifiable weight on a proxy feature (referral) that correlates with privilege and background rather than merit, making the AI system harder to defend in an audit.


In [28]:
# Full rank matrix
X_full = np.array([
    [5, 82, 7, 1],
    [3, 91, 8, 0],
    [7, 78, 6, 1],
    [4, 85, 9, 0]
])
# Rank tells us how many unique pieces of information exist in a matrix.
# Redundant columns = same information counted twice = hidden bias amplification
print("Rank (full):", np.linalg.matrix_rank(X_full))

# Rank-deficient: feature 3 = feature 0 * 2
X_deficient = np.array([
    [5, 82, 7, 10],
    [3, 91, 8,  6],
    [7, 78, 6, 14],
    [4, 85, 9,  8]
])
print("Rank (deficient):", np.linalg.matrix_rank(X_deficient))

# Check: is column 3 really column 0 * 2?
print("\nColumn 0:", X_deficient[:, 0])
print("Column 3:", X_deficient[:, 3])
print("Ratio:", X_deficient[:, 3] / X_deficient[:, 0])

Rank (full): 4
Rank (deficient): 3

Column 0: [5 3 7 4]
Column 3: [10  6 14  8]
Ratio: [2. 2. 2. 2.]
